### ISSUE TITLE
docker安装时事件订阅的request URL 显示“Your URL didn't respond” 请问该咋解决呢

### ISSUE THREAD

**Issue by ningyuwhut** [madawei2699/myGPTReader#31]
参考“https://github.com/madawei2699/myGPTReader/blob/main/docs/how-to-install/docker.md” 在自己的vps上配置，在
“配置 slack 的事件订阅” 这一步一直显示 “Your URL didn't respond.“，同时页面上还有一个提示“The server couldn’t be reached at your request URL”，填的地址格式也是”http://你的ip:端口/slack/events“ 。

<img width="707" alt="image" src="https://user-images.githubusercontent.com/1762074/229986482-4227abab-4a4c-475a-8e00-820de3f85e15.png">

但是换成另外一个端口1989，就显示“Your request URL responded with an HTTP error”。1989是我启动的gost服务的端口。
<img width="691" alt="image" src="https://user-images.githubusercontent.com/1762074/229986592-36bed70a-f5cb-4afd-a8ed-43ba43c39d21.png">

我的vps上显示

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/1762074/229356020-7fcf039d-ce7a-46c0-ade0-e8e2dc96755f.png">

```
root       39329  0.0  0.8 712656  8408 ?        Sl   02:13   0:04 /usr/bin/containerd-shim-runc-v2 -namespace moby -id fb3e322b046393bd2e5a273b48e2bedb4ac3eff1ea0f8024ec73e06afb6325fc -address /run/containerd/containerd.sock
root       39351  0.0  1.7  26224 17728 ?        Ss   02:13   0:11  \_ /usr/local/bin/python /usr/local/bin/gunicorn app.server:app
root       39401  0.0 11.6 319688 117612 ?       Sl   02:13   0:05      \_ /usr/local/bin/python /usr/local/bin/gunicorn app.server:app
```

docker的几个进程：

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/1762074/229356122-2de4584b-4f2f-47d5-ad92-dba467bb595e.png">

在vps上ping 这台机器的ip是可以ping通的，但是ping8080端口却ping不通，但是lsof 命令显示8080是打开的

```
root@sweet-kitten-1:~# lsof -i:8080

COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 39309 root    4u  IPv4 540438      0t0  TCP *:http-alt (LISTEN)
```
显示有进程在监听8080端口

docker-compose ps的输出如下：
```
root@sweet-kitten-1:~/myGPTReader_config# docker-compose ps
NAME                       IMAGE               COMMAND                  SERVICE             CREATED             STATUS              PORTS
mygptreader_config-web-1   gptreader:lastest   "gunicorn app.server…"   web                 12 hours ago        Up 12 hours         0.0.0.0:8080->8080/tcp, :::8080->8080/tcp
```

请教一下，这个会是哪里的问题，还需要检查什么配置吗？多谢~

**Comment by hurner** [comment]
我这边也遇到同样的问题了，换了端口slack也一直显示“Your URL didn't respond.”

**Comment by hurner** [comment]
network_mode: "host"

使用主机网络可以。不知道为什么映射端口就是不行 。

**Comment by ningyuwhut** [comment]
@hurner 多谢，我周末再试一下~
